name:               "Uta Büchler"
description:        "PhD in Computer vision"

url:                ""
author:             "thinker3197"
email:              "jhondoe@abc.com"
twitter:            "jhondoe"
email:              "jhondoe@abc.com"
github:             "jhondoe"
pinterest:          "jhondoe"
linkedin:           "jhondoe"
facebook:           "jhondoe"

disqus_shortname:   "thinker3197"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Career"
    href:           "/career"
  - name:           "Publications"
    href:           "/publications"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate

highlighter: rouge
