name:               "Uta Büchler"
description:        "Ph.D. student in Computer Vision"

url:                "https://utabuechler.github.io/homepage"
author:             "utabuechler"
email:              "utabuechler@web.de"
#twitter:            "jhondoe"
#email:              "jhondoe@abc.com"
github:             "utabuechler"
#pinterest:          "jhondoe"
#linkedin:           "jhondoe"
#facebook:           "jhondoe"

disqus_shortname:   "utabuechler"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            "https://utabuechler.github.io/homepage"
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Home"
    href:           "https://utabuechler.github.io/homepage"
  - name:           "About Me"
    href:           "https://utabuechler.github.io/homepage/aboutme"
  - name:           "Career"
    href:           "https://utabuechler.github.io/homepage/career"
  - name:           "Publications"
    href:           "https://utabuechler.github.io/homepage/publications"
  - name:           "Contact"
    href:           "https://utabuechler.github.io/homepage/contact"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate

highlighter: rouge
