name:               "Uta Büchler"
description:        "Ph.D. student in Computer Vision"

url:                ""
author:             "utabuechler"
email:              "utabuechler@web.de"
#twitter:            "jhondoe"
#email:              "jhondoe@abc.com"
github:             "utabuechler"
#pinterest:          "jhondoe"
#linkedin:           "jhondoe"
#facebook:           "jhondoe"

disqus_shortname:   "utabuechler"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

skills:
  - label: Topic
    id : cs
    aspects: Computer \n vision, Machine \n learning, Deep \n learning, Optimization, Teaching
    percentage: 90, 80, 80, 50, 60
  - label: Languages
    id : cs1
    aspects: Python, Matlab, C++, Java, SPSS, LaTex
    percentage: 90, 90, 60, 50, 50, 80
    
nav:
  - name:           "Home"
    href:           "/"
  - name:           "About Me"
    href:           "/aboutme"
  - name:           "Career"
    href:           "/career"
  - name:           "Publications"
    href:           "/publications"
  - name:           "Contact"
    href:           "/contact"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate

highlighter: rouge
